### PR TITLE
Fixed httphijack rw loop

### PR DESCRIPTION
**Pull request by Frugghi**
Using the tiny example VMs the api-proxy logs `E0830 20:30:12.520783       1 httphijack.go:95] < (req id: mjL7tuw2iqxYLA==) Error writing data: write tcp 172.17.0.2:8087->172.17.0.1:57267: write: broken pipe` every time it enters in the `rwloop` of `httphijack.go`.

This should fix the issue and keep the same behavior.

Tested on Windows with the Vagrant VMs.

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@Frugghi this is not assigned to anybody and there is no indication of whether it has been tested

**Comment by Frugghi** [comment]
@MikeSpreitzer Mariusz was testing it, I assign it to him

**Comment by Frugghi** [comment]
On hold, requires more investigation.

**Comment by Frugghi** [comment]
After further investigation I don't think this is the best solution, I'll open another PR later.

**Pull request closed without merging**
