### PR TITLE
Inventory contract no longer requires unused groups 

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
Revised the inventory contract so that a group that is not used does
not have to be defined in the inventory.

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
This work was started by @suppandi

**Comment by huang195** [comment]
Why are we only enabling vip when we're deploying to a mesos cluster. This is making vip not work in a kube-only deployment.

**Comment by pdettori** [comment]
I agree, VIP should be enabled in kube only deployment as well.

**Comment by MikeSpreitzer** [comment]
Good catch, sorry I let that through.  I will open an issue to fix this.

**Pull request merged**
