### PR TITLE
uses the correct name for the  docker image

### PR DESCRIPTION
**Pull request by jsloyer**
corrects the name of the built docker image in `builddocker.sh` to `containercafe/api-proxy`

### CODE REVIEW

**Comment by jsloyer** [comment]
Closing as the `rundocker.sh` script has a `-i` parameter to override the image

**Comment by MikeSpreitzer** [comment]
Is there a documentation change implied here?

**Comment by mrsabath** [comment]
I don't believe the should be a direct push to public github registry. The image should be build locally first, then it can be pushed to the public registry. So perhaps adding a flag `builddocker.sh -push containercafe/api-proxy` would be better solution. 

BTW, we should start including the image tags that would correspond to the commit id

**Comment by jsloyer** [comment]
Yeah Im fine with that.  I think we just need some documentation stating if you are running locally you need to use `-i api-proxy` when running `rundocker.sh`

**Pull request closed without merging**
